# Generated by Django 5.0.1 on 2024-01-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthday', models.DateField(default='01/01/1970', null=True)),
                ('age', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('titleRu', models.CharField(blank=True, max_length=150, null=True)),
                ('agelimitation', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('descriptionHTML', models.TextField(blank=True, null=True)),
                ('imdb', models.CharField(blank=True, max_length=15, null=True)),
                ('poster', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollname', models.CharField(blank=True, max_length=50, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.country')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvcat.movie')),
            ],
        ),
    ]
