# Generated by Django 5.0.1 on 2024-01-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
