# Generated by Django 5.0.1 on 2024-01-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0004_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.actor'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.movie'),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.actor'),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.movie'),
        ),
    ]
