# Generated by Django 5.0.1 on 2024-01-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0005_alter_moviecast_actor_alter_moviecast_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
