# Generated by Django 5.0.1 on 2024-01-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0009_movie_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_premier',
            field=models.DateField(blank=True, null=True),
        ),
    ]
