# Generated by Django 5.0.1 on 2024-01-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0010_movie_date_premier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
