# Generated by Django 5.0.1 on 2024-01-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0011_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.country'),
        ),
    ]
