# Generated by Django 5.0.1 on 2024-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0012_actor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='stringnimber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True),
        ),
    ]
