# Generated by Django 5.0.1 on 2024-01-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0013_moviecast_stringnimber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvcat.country'),
        ),
    ]
