# Generated by Django 5.0.1 on 2024-01-27 16:53

import mvcat.models.Actors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0014_alter_actor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150, validators=[mvcat.models.Actors.validate_name]),
        ),
    ]
