# Generated by Django 4.2.9 on 2024-02-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0015_alter_actor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, default='01/01/1970', null=True),
        ),
    ]
