# Generated by Django 4.2.9 on 2024-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0016_alter_actor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
