# Generated by Django 4.2.9 on 2024-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0019_moviejanres'),
    ]

    operations = [
        migrations.AddField(
            model_name='janres',
            name='nameRu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='janres',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='janres',
            name='picturePath',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
