# Generated by Django 4.2.9 on 2024-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcat', '0020_janres_nameru_alter_janres_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='janres',
            field=models.ManyToManyField(through='mvcat.MovieJanres', to='mvcat.janres'),
        ),
    ]
